import { SaveStripeHandler } from "../use-case/handlers/SaveStripeHandler";
import { FindStripeCustomerHandler } from "../use-case/handlers/FindStripeCustomerHandler";
import { StripeMongoDBRepo } from "./db/StripeMongoDBRepo";
import { FindStripeCustomer } from "../use-case/FindStripeCustomer";
import { SaveStripe } from "../use-case/SaveStripe";
import { PaymentIntent } from "../use-case/PaymentIntent";
import { StripePayments } from "./StripePayments";
import { PaymentIntentHandler } from "../use-case/handlers/PaymentIntentHandler";
import { UpdateStripe } from "../use-case/UpdateStripe";
import { UpdateStripeHandler } from "../use-case/handlers/UpdateStripeHandler";
import { GetPaymentDetailsHandler } from "../use-case/handlers/GetPaymentDetailsHandler";
import { GetPaymentDetails } from "../use-case/GetPaymentDetails";
import { CreateStripeCustomer } from "../use-case/CreateStripeCustomer";
import { CreateStripeCustomerHandler } from "../use-case/handlers/CreateStripeCustomerHandler";

const stripeRepo = new StripeMongoDBRepo();
const stripePayments = new StripePayments();
const saveStripe = new SaveStripe(stripeRepo);
const findStripe = new FindStripeCustomer(stripeRepo);
const paymentIntent = new PaymentIntent(stripePayments);
const updateStripe = new UpdateStripe(stripeRepo);
const getDetails = new GetPaymentDetails(stripePayments);
const createStripeCustomer = new CreateStripeCustomer(stripePayments);

export const saveStripeHandler = new SaveStripeHandler(saveStripe);
export const findCustomerHandler = new FindStripeCustomerHandler(findStripe);
export const paymentIntentHandler = new PaymentIntentHandler(paymentIntent);
export const updateStripeHandler = new UpdateStripeHandler(updateStripe);
export const getPaymentDetailsHandler = new GetPaymentDetailsHandler(getDetails);
export const createStripeCustomerHandler = new CreateStripeCustomerHandler(createStripeCustomer);